#
# Poetry project to manage Odoo's deps with Poetry.
#
# To put together this file and the corresponding lock file from scratch:
# - start our Nix shell
# - download `odoo_14.0.20231205.tar.gz`
# - extract and `cd` into extracted dir
# - run `poetry init`
# - edit generated `pyproject.toml` to change the `packages` include
#   to `odoo` and copy over Python deps from `requirements.txt`
# - run `poetry lock`
# - copy over both `pyproject.toml` and `poetry.lock` to our Odoo
#   Nix package source dir
#

[tool.poetry]
name = "Odoo Server 16.0"
version = "16.0.0"
description = "Odoo Server packaged with Poetry"
authors = ["Odoo S.A. info@odoo.com"]
license = "LGPL-3"
readme = "README.md"

# The odoo_14.0.20231205.tar.gz tarball has all the Odoo code under
# the `odoo` dir, hence the below package include.
packages = [{include = "odoo"}]


[tool.poetry.dependencies]

# Our Python's version---i.e. the one we'd like to run Odoo with.
python = "^3.11"

# Deps from Odoo's `requirements.txt` in the `odoo_14.0.20231205.tar.gz`
# tarball.

Babel = "2.9.1"
chardet = "4.0.0"
decorator = "4.4.2"
docutils = "0.16"
ebaysdk = "2.1.5"
freezegun = "0.3.15"
gevent = "22.10.2"
greenlet = "2.0.2"
idna = "2.10"
Jinja2 = "3.1.2"
libsass = "0.20.1"
lxml = "4.9.3"
MarkupSafe = "2.1.2"
num2words = "0.5.9"
ofxparse = "0.21"
passlib = "1.7.4"
Pillow = "9.4.0"
polib = "1.1.0"
psutil = "5.9.4"
psycopg2 = "2.9.5"
pydot = "1.4.2"
cryptography = "41.0.1"
pyopenssl = "23.2.0"
PyPDF2 = "2.12.1"
pyserial = "3.5"
python-dateutil = "2.8.1"
python-ldap = "3.4.0"
python-stdnum = "1.16"
pytz = "*"
pyusb = "1.2.1"
qrcode = "6.1"
reportlab = "3.6.12"
requests = "2.25.1"
urllib3 = "1.26.5"
vobject = "0.9.6.1"
Werkzeug = "2.0.2"
xlrd = "1.2.0"
XlsxWriter = "1.1.2"
xlwt = "1.3.0"
zeep = "4.0.0"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
